import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { handleSetUserInfo } from "@/store/userSlice";
import { Box, Container } from "@chakra-ui/react";

export default function Home() {
  const dispatch = useDispatch();
  const userInfo = useSelector((state: any) => state.user.userInfo);

  useEffect(() => {
    dispatch(handleSetUserInfo());
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Box>{JSON.stringify(userInfo)}</Box>
      </Container>
    </>
  );
}
