import Head from "next/head";
import Image from "next/image";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { handleSetUserInfo } from "@/store/userSlice";

export default function Home() {
  const dispatch = useDispatch();
  const userInfo = useSelector((state: any) => state.user.userInfo);

  useEffect(() => {
    dispatch(handleSetUserInfo());
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex bg-black text-white">
        <p>{JSON.stringify(userInfo)}</p>
      </div>
    </>
  );
}
